# Generated by Django 5.0.1 on 2024-01-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('no_of_guests', models.IntegerField(default=0)),
                ('bookingdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.DeleteModel(
            name='booking_table',
        ),
        migrations.DeleteModel(
            name='menu_table',
        ),
    ]
